name: Docker Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - '1.24/**'
      - '1.25/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            1.24:
              - '1.24/**'
            1.25:
              - '1.25/**'

  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.versions != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(needs.detect-changes.outputs.versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-micro-tool:${{ matrix.version }}
          cache-from: type=gha,scope=${{ matrix.version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.version }}